---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: source-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rsync-source

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rsync-source
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - anyuid
    resources:
      - securitycontextconstraints
    verbs:
      - use

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rsync-source
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rsync-source
subjects:
  - kind: ServiceAccount
    name: rsync-source

---
apiVersion: batch/v1
kind: Job
metadata:
  name: volsync-rsync-source
spec:
  template:
    metadata:
      name: volsync-rsync-source
      labels:
        app.kubernetes.io/name: rsync-source
        app.kubernetes.io/component: mover
        app.kubernetes.io/part-of: volsync
    spec:
      containers:
        - name: rsync
          command: ["/bin/bash", "-c", "/source.sh"]
          env:
            - name: DESTINATION_ADDRESS
              value: volsync-rsync-destination.volsync.svc.cluster.local
          image: quay.io/backube/volsync-mover-rsync:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: data
              mountPath: /data
            - name: keys
              mountPath: /keys
      restartPolicy: Never
      serviceAccount: rsync-source
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: source-data
            readOnly: true
        - name: keys
          secret:
            secretName: source-secret
            defaultMode: 0600
