apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: volsync
    app.kubernetes.io/instance: replicationdestination-viewer-role
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: volsync
    app.kubernetes.io/part-of: volsync
  name: volsync-replicationdestination-viewer-role
rules:
- apiGroups:
  - volsync.backube
  resources:
  - replicationdestinations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - volsync.backube
  resources:
  - replicationdestinations/status
  verbs:
  - get
