apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: volsync
    app.kubernetes.io/instance: metrics-reader
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: volsync
    app.kubernetes.io/part-of: volsync
  name: volsync-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
