---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysql
    app.kubernetes.io/component: mysql
    template: mysql-persistent-template
  name: mysql
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    tier: mysql
status:
  loadBalancer: {}
