# permissions for end users to edit replicationsources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: replicationsource-editor-role
rules:
- apiGroups:
  - volsync.backube
  resources:
  - replicationsources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - volsync.backube
  resources:
  - replicationsources/status
  verbs:
  - get
