# permissions for end users to edit replicationsources.
#
# This rule is not used by the project volsync itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the volsync.backube.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: volsync
    app.kubernetes.io/instance: replicationsource-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: volsync
    app.kubernetes.io/part-of: volsync
    app.kubernetes.io/managed-by: kustomize
  name: replicationsource-editor-role
rules:
- apiGroups:
  - volsync.backube
  resources:
  - replicationsources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - volsync.backube
  resources:
  - replicationsources/status
  verbs:
  - get
