# This rule is not used by the project volsync itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over volsync.backube.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: volsync
    app.kubernetes.io/instance: replicationsource-admin-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: volsync
    app.kubernetes.io/part-of: volsync
    app.kubernetes.io/managed-by: kustomize
  name: replicationsource-admin-role
rules:
- apiGroups:
  - volsync.backube
  resources:
  - replicationsources
  verbs:
  - '*'
- apiGroups:
  - volsync.backube
  resources:
  - replicationsources/status
  verbs:
  - get
