{{- if not .Values.metrics.disableAuth }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "volsync.fullname" . }}-metrics-reader
  labels:
    {{- include "volsync.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
{{- end }}
