## Append samples you want in your CSV to this file as resources ##
resources:
- volsync_v1alpha1_replicationsource.yaml
- volsync_v1alpha1_replicationdestination.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
