---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mover-rclone-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2-csi

---
apiVersion: batch/v1
kind: Job
metadata:
  name: mover-rclone
spec:
  template:
    metadata:
      name: mover-rclone
    spec:
      containers:
        - name: scribe-mover-rclone
          image: quay.io/backube/scribe-mover-rclone
          command: ["./active.sh"]
          env:
            - name: RCLONE_CONFIG
              value: /rclone-config/rclone.conf
            - name: RCLONE_DEST_PATH
              value: scribe-test-bucket
            - name: DIRECTION
              value: destination
            - name: MOUNT_PATH
              value: /data
            - name: RCLONE_CONFIG_SECTION
              value: aws-s3-bucket
          volumeMounts:
            # name must match the volume name below
            - name: rclone-secret
              mountPath: /rclone-config/
              readOnly: true
            - name: snapshot-data
              mountPath: /data
      volumes:
        - name: rclone-secret
          secret:
            secretName: rclone-secret
        - name: snapshot-data
          persistentVolumeClaim:
            claimName: mover-rclone-pv-claim
      restartPolicy: Never
