---
# https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default
ignore: |
  bundle/**
  config/**
  internal/controller/test/scc-crd.yml
  internal/controller/test/populator.storage.k8s.io_volumepopulators.yaml
  custom-scorecard-tests/**
  hack/crds/*
  helm/volsync/**
  .krew.yaml
  .tekton/*
rules:
  comments:  # renovate-bot dosen't put 2 spaces before the version number
    ignore: |
      .github/workflows/*
  indentation:
    indent-sequences: consistent
  line-length:
    allow-non-breakable-inline-mappings: true
    ignore: |
      kubectl-volsync/volsync.yaml
      test-kuttl/**
      test-e2e/**
