---
- hosts: localhost
  tags:
    - e2e
    - kopia
    - source-path-override
    - unprivileged
  vars:
    kopia_secret_name: kopia-secret-pathoverride
  tasks:
    - include_role:
        name: create_namespace

    - include_role:
        name: gather_cluster_info

    # We're running everything as a normal user
    - name: Define podSecurityContext
      ansible.builtin.set_fact:
        podSecurityContext:
          fsGroup: 5678
          runAsGroup: 5678
          runAsNonRoot: true
          runAsUser: 1234
          seccompProfile:
            type: RuntimeDefault
      when: not cluster_info.is_openshift

    - include_role:
        name: create_kopia_secret
      vars:
        minio_namespace: minio

    - name: Create source PVC
      kubernetes.core.k8s:
        state: present
        definition:
          kind: PersistentVolumeClaim
          apiVersion: v1
          metadata:
            name: data-source
            namespace: "{{ namespace }}"
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi

    - name: Write data into the source PVC
      include_role:
        name: write_to_pvc
      vars:
        data: 'path-override-test-data'
        path: '/datafile'
        pvc_name: 'data-source'

    # Test source path override - backup from /data but show as /var/lib/myapp/data
    - name: Backup with source path override (w/ mSC)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: volsync.backube/v1alpha1
          kind: ReplicationSource
          metadata:
            name: source
            namespace: "{{ namespace }}"
          spec:
            sourcePVC: data-source
            trigger:
              manual: override-backup
            kopia:
              repository: "{{ kopia_secret_name }}"
              username: "testapp"
              hostname: "override-test"
              sourcePathOverride: "/var/lib/myapp/data"
              compression: zstd
              parallelism: 1
              copyMethod: Snapshot
              cacheCapacity: 1Gi
              moverSecurityContext: "{{ podSecurityContext }}"
      when: podSecurityContext is defined

    - name: Backup with source path override (w/o mSC)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: volsync.backube/v1alpha1
          kind: ReplicationSource
          metadata:
            name: source
            namespace: "{{ namespace }}"
          spec:
            sourcePVC: data-source
            trigger:
              manual: override-backup
            kopia:
              repository: "{{ kopia_secret_name }}"
              username: "testapp"
              hostname: "override-test"
              sourcePathOverride: "/var/lib/myapp/data"
              compression: zstd
              parallelism: 1
              copyMethod: Snapshot
              cacheCapacity: 1Gi
      when: podSecurityContext is not defined

    - name: Wait for backup to complete
      kubernetes.core.k8s_info:
        api_version: volsync.backube/v1alpha1
        kind: ReplicationSource
        name: source
        namespace: "{{ namespace }}"
      register: res
      until: >
        res.resources | length > 0 and
        res.resources[0].status.lastManualSync is defined and
        res.resources[0].status.lastManualSync=="override-backup" and
        res.resources[0].status.latestMoverStatus is defined and
        res.resources[0].status.latestMoverStatus.result == "Successful" and
        res.resources[0].status.latestMoverStatus.logs is search("Using source path override: /var/lib/myapp/data") and
        res.resources[0].status.latestMoverStatus.logs is search("Using username override: testapp") and
        res.resources[0].status.latestMoverStatus.logs is search("Using hostname override: override-test") and
        res.resources[0].status.latestMoverStatus.logs is search("snapshot.*created") and
        res.resources[0].status.latestMoverStatus.logs is search("Kopia completed in.*")
      delay: 1
      retries: 300

    # Verify that we can restore from the snapshot using the same identity
    - name: Create dest PVC (restore volume)
      kubernetes.core.k8s:
        state: present
        definition:
          kind: PersistentVolumeClaim
          apiVersion: v1
          metadata:
            name: data-dest
            namespace: "{{ namespace }}"
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi

    - name: Run pvc affinity pod
      include_role:
        name: pvc_affinity_pod
      vars:
        pvc_names:
          - data-source
          - data-dest

    - name: Restore data with matching identity (w/ mSC)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: volsync.backube/v1alpha1
          kind: ReplicationDestination
          metadata:
            name: restore
            namespace: "{{ namespace }}"
          spec:
            trigger:
              manual: restore-override
            kopia:
              repository: "{{ kopia_secret_name }}"
              username: "testapp"       # Must match source identity
              hostname: "override-test" # Must match source identity
              destinationPVC: data-dest
              copyMethod: Direct
              cacheCapacity: 1Gi
              moverSecurityContext: "{{ podSecurityContext }}"
      when: podSecurityContext is defined

    - name: Restore data with matching identity (w/o mSC)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: volsync.backube/v1alpha1
          kind: ReplicationDestination
          metadata:
            name: restore
            namespace: "{{ namespace }}"
          spec:
            trigger:
              manual: restore-override
            kopia:
              repository: "{{ kopia_secret_name }}"
              username: "testapp"       # Must match source identity
              hostname: "override-test" # Must match source identity
              destinationPVC: data-dest
              copyMethod: Direct
              cacheCapacity: 1Gi
      when: podSecurityContext is not defined

    - name: Wait for restore to complete
      kubernetes.core.k8s_info:
        api_version: volsync.backube/v1alpha1
        kind: ReplicationDestination
        name: restore
        namespace: "{{ namespace }}"
      register: res
      until: >
        res.resources | length > 0 and
        res.resources[0].status.lastManualSync is defined and
        res.resources[0].status.lastManualSync=="restore-override" and
        res.resources[0].status.latestMoverStatus is defined and
        res.resources[0].status.latestMoverStatus.result == "Successful" and
        res.resources[0].status.latestMoverStatus.logs is search("Using username override: testapp") and
        res.resources[0].status.latestMoverStatus.logs is search("Using hostname override: override-test") and
        res.resources[0].status.latestMoverStatus.logs is search("restoring.*") and
        res.resources[0].status.latestMoverStatus.logs is search("Kopia completed in.*")
      delay: 1
      retries: 300

    - name: Shutdown pvc affinity pod
      include_role:
        name: pvc_affinity_pod
        tasks_from: "delete"

    - name: Verify contents match despite path override
      include_role:
        name: compare_pvc_data
      vars:
        pvc1_name: data-source
        pvc2_name: data-dest

    # Test negative case: verify that restore fails with mismatched identity
    - name: Create second dest PVC for negative test
      kubernetes.core.k8s:
        state: present
        definition:
          kind: PersistentVolumeClaim
          apiVersion: v1
          metadata:
            name: data-dest-fail
            namespace: "{{ namespace }}"
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi

    - name: Try to restore with wrong identity (should find no snapshots)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: volsync.backube/v1alpha1
          kind: ReplicationDestination
          metadata:
            name: restore-fail
            namespace: "{{ namespace }}"
          spec:
            trigger:
              manual: restore-fail
            kopia:
              repository: "{{ kopia_secret_name }}"
              username: "wronguser"    # Different from source
              hostname: "wronghost"    # Different from source  
              destinationPVC: data-dest-fail
              copyMethod: Direct
              cacheCapacity: 1Gi

    - name: Wait for failed restore (should complete but restore nothing)
      kubernetes.core.k8s_info:
        api_version: volsync.backube/v1alpha1
        kind: ReplicationDestination
        name: restore-fail
        namespace: "{{ namespace }}"
      register: res
      until: >
        res.resources | length > 0 and
        res.resources[0].status.lastManualSync is defined and
        res.resources[0].status.lastManualSync=="restore-fail" and
        res.resources[0].status.latestMoverStatus is defined and
        res.resources[0].status.latestMoverStatus.result == "Successful" and
        res.resources[0].status.latestMoverStatus.logs is search("No eligible snapshots found|=== No data will be restored ===")
      delay: 1
      retries: 300