---
- hosts: localhost
  tags:
    - e2e
    - rsync_tls
    - privileged
  tasks:
    - name: Create namespace
      include_role:
        name: create_namespace

    - name: Enable privileged movers
      include_role:
        name: enable_privileged_mover

    - name: Create ReplicationDestination
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: volsync.backube/v1alpha1
          kind: ReplicationDestination
          metadata:
            name: test
            namespace: "{{ namespace }}"
          spec:
            rsyncTLS:
              copyMethod: Snapshot
              capacity: 1Gi
              accessModes:
                - ReadWriteOnce

    - name: Create source PVC
      kubernetes.core.k8s:
        state: present
        definition:
          kind: PersistentVolumeClaim
          apiVersion: v1
          metadata:
            name: data-source
            namespace: "{{ namespace }}"
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi

    - name: Write data into the source PVC
      include_role:
        name: write_to_pvc
      vars:
        data: 'data'
        path: '/datafile'
        pvc_name: 'data-source'

    - name: Wait for key and address to be ready
      kubernetes.core.k8s_info:
        api_version: volsync.backube/v1alpha1
        kind: ReplicationDestination
        name: test
        namespace: "{{ namespace }}"
      register: res
      until: >
        res.resources | length > 0 and
        res.resources[0].status.rsyncTLS is defined and
        res.resources[0].status.rsyncTLS.keySecret is defined and
        res.resources[0].status.rsyncTLS.address is defined
      delay: 1
      retries: 300

    - name: Create ReplicationSource
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: volsync.backube/v1alpha1
          kind: ReplicationSource
          metadata:
            name: source
            namespace: "{{ namespace }}"
          spec:
            sourcePVC: data-source
            trigger:
              schedule: "0 0 1 1 *"
            rsyncTLS:
              keySecret: "{{ res.resources[0].status.rsyncTLS.keySecret }}"
              address: "{{ res.resources[0].status.rsyncTLS.address }}"
              copyMethod: Snapshot

    - name: Check status of replicationsource
      kubernetes.core.k8s_info:
        api_version: volsync.backube/v1alpha1
        kind: ReplicationSource
        name: source
        namespace: "{{ namespace }}"
      register: res
      until: >
        res.resources | length > 0 and
        res.resources[0].status.lastSyncDuration is defined and
        res.resources[0].status.lastSyncTime is defined and
        res.resources[0].status.latestMoverStatus is defined and
        res.resources[0].status.latestMoverStatus.result == "Successful" and
        res.resources[0].status.latestMoverStatus.logs is search("sent.*bytes.*received.*bytes.*") and
        res.resources[0].status.latestMoverStatus.logs is search("rsync completed in.*")
      delay: 1
      retries: 900

    - name: Wait for sync to complete
      kubernetes.core.k8s_info:
        api_version: volsync.backube/v1alpha1
        kind: ReplicationDestination
        name: test
        namespace: "{{ namespace }}"
      register: res
      until: >
        res.resources | length > 0 and
        res.resources[0].status.latestImage is defined and
        res.resources[0].status.latestImage.kind == "VolumeSnapshot" and
        res.resources[0].status.latestMoverStatus is defined and
        res.resources[0].status.latestMoverStatus.result == "Successful"
      delay: 1
      retries: 900

    - name: Convert latestImage to PVC
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: data-dest
            namespace: "{{ namespace }}"
          spec:
            accessModes:
              - ReadWriteOnce
            dataSource:
              kind: VolumeSnapshot
              apiGroup: snapshot.storage.k8s.io
              name: "{{ res.resources[0].status.latestImage.name }}"
            resources:
              requests:
                storage: 1Gi

    - name: Verify contents of PVC
      include_role:
        name: compare_pvc_data
      vars:
        pvc1_name: data-source
        pvc2_name: data-dest
        timeout: 900
