---
- hosts: localhost
  tags:
    - e2e
    - rsync
  tasks:
    - include_role:
        name: create_namespace

    - name: Create ReplicationDestination
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: volsync.backube/v1alpha1
          kind: ReplicationDestination
          metadata:
            name: test
            namespace: "{{ namespace }}"
          spec:
            rsync:
              copyMethod: Snapshot
              capacity: 1Gi
              accessModes:
                - ReadWriteOnce

    - name: Create source PVC
      kubernetes.core.k8s:
        state: present
        definition:
          kind: PersistentVolumeClaim
          apiVersion: v1
          metadata:
            name: data-source
            namespace: "{{ namespace }}"
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi

    - name: Write data into the source PVC
      include_role:
        name: write_to_pvc
      vars:
        data: 'data'
        path: '/datafile'
        pvc_name: 'data-source'

    - name: Wait for ssh keys and address to be ready
      kubernetes.core.k8s_info:
        api_version: volsync.backube/v1alpha1
        kind: ReplicationDestination
        name: test
        namespace: "{{ namespace }}"
      register: res
      until: >
        res.resources | length > 0 and
        res.resources[0].status.rsync is defined and
        res.resources[0].status.rsync.sshKeys is defined and
        res.resources[0].status.rsync.address is defined
      delay: 1
      retries: 300

    - name: Create ReplicationSource
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: volsync.backube/v1alpha1
          kind: ReplicationSource
          metadata:
            name: source
            namespace: "{{ namespace }}"
          spec:
            sourcePVC: data-source
            trigger:
              manual: firstsync
            rsync:
              sshKeys: "{{ res.resources[0].status.rsync.sshKeys }}"
              address: "{{ res.resources[0].status.rsync.address }}"
              copyMethod: Snapshot

    # Using volume populator - no need to wait for RD to be done yet before creating the pvc
    - name: Convert latestImage to PVC Using VolumePopulator
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: data-dest-1
            namespace: "{{ namespace }}"
          spec:
            accessModes:
              - ReadWriteOnce
            dataSourceRef:
              kind: ReplicationDestination
              apiGroup: volsync.backube
              name: test
            resources:
              requests:
                storage: 1Gi

    - name: Wait for sync to complete
      kubernetes.core.k8s_info:
        api_version: volsync.backube/v1alpha1
        kind: ReplicationDestination
        name: test
        namespace: "{{ namespace }}"
      register: res
      until: >
        res.resources | length > 0 and
        res.resources[0].status.latestImage is defined and
        res.resources[0].status.latestImage.kind == "VolumeSnapshot"
      delay: 1
      retries: 900

    - name: Save name of first snapshot
      ansible.builtin.set_fact:
        first_snap: "{{ res.resources[0].status.latestImage.name }}"

    - name: Verify contents of PVC
      include_role:
        name: compare_pvc_data
      vars:
        pvc1_name: data-source
        pvc2_name: data-dest-1
        timeout: 900

    - name: Update data in the source PVC
      include_role:
        name: write_to_pvc
      vars:
        data: 'moredata'
        path: '/datafile'
        pvc_name: 'data-source'

    - name: Trigger 2nd sync from source volume
      kubernetes.core.k8s:
        state: patched
        definition:
          apiVersion: volsync.backube/v1alpha1
          kind: ReplicationSource
          metadata:
            name: source
            namespace: "{{ namespace }}"
          spec:
            trigger:
              manual: secondsync

    - name: Wait for 2nd sync to complete
      kubernetes.core.k8s_info:
        api_version: volsync.backube/v1alpha1
        kind: ReplicationDestination
        name: test
        namespace: "{{ namespace }}"
      register: res
      until: >
        res.resources | length > 0 and
        res.resources[0].status.latestImage is defined and
        res.resources[0].status.latestImage.name != first_snap
      delay: 1
      retries: 900

    - name: Save name of second snapshot
      ansible.builtin.set_fact:
        second_snap: "{{ res.resources[0].status.latestImage.name }}"

    # This time create the pvc after RD is finished to make sure we get the latest
    - name: Convert latestImage to PVC
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: data-dest-2
            namespace: "{{ namespace }}"
          spec:
            accessModes:
              - ReadWriteOnce
            dataSourceRef:
              kind: ReplicationDestination
              apiGroup: volsync.backube
              name: test
            resources:
              requests:
                storage: 1Gi

    - name: Verify contents of PVC
      include_role:
        name: compare_pvc_data
      vars:
        pvc1_name: data-source
        pvc2_name: data-dest-2
        timeout: 900

    - name: Ensure first snapshot was deleted
      kubernetes.core.k8s_info:
        api_version: snapshot.storage.k8s.io/v1
        kind: VolumeSnapshot
        name: "{{ first_snap }}"
        namespace: "{{ namespace }}"
      register: res
      until: res.resources | length == 0
      delay: 1
      retries: 60

    - name: Ensure destination has correct contents
      include_role:
        name: pvc_has_data
      vars:
        data: 'moredata'
        path: '/datafile'
        pvc_name: 'data-dest-2'
